GSE70138_Broad_LINCS_Level3_INF_mlr12k_n115209x22268_2015-12-31.gct.gz:
	wget -N ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE70nnn/GSE70138/suppl/$@

io.R:
	wget -N https://raw.githubusercontent.com/cmap/l1ktools/master/R/cmap/$@
